name: rustacean-authorship-action
description: GitHub Action to Verify PR Authorship
author: Esteban Borai <estebanborai@gmail.com> (https://estebanborai.com)

inputs:
  pr_author:
    required: true
    description: PR Author
  token:
    required: true
    description: GitHub Token Used to interact with the GitHub API
    default: ${{ github.token }}

on:
  pull_request:
    branches: [ "main" ]
#  Here the action will get the PR number
      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Here the action will get the diff
      - name: Get Pull Request Diffing Files
        id: diff
        run: gh pr diff --name-only

        # Can I get the diff in an environment variable?

    

runs:
  using: composite
  steps:
    - shell: bash
      name: Download Action
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh release download \
          --repo rustacean-sh/rustacean-authorship-action \
          --pattern 'rustacean-authorship-action-ubuntu-latest'

    - id: run
      shell: bash
      name: Run Action
      run: |
        chmod +x ./rustacean-authorship-action-ubuntu-latest
        ./rustacean-authorship-action-ubuntu-latest "${{ inputs.pr_author }}"

  
    
