[package]
name = "rustacean-authorship-action"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.42.0", features = ["full"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
url = "2.3.1"