on:
  pull_request:
    types: [opened, reopened]
  
    
      jobs:
        setup:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Source
            uses: actions/checkout@v4

           
          - name: call Github  action
            id: pr
           
            env:
              PR_NUMBER: ${{ github.event.number }}
              PR_AUTHOR: ${{ github.actor }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            run: cargo run PR_AUTHOR PR_NUMBER GITHUB_TOKEN
