name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Perform Test
        uses: ./
        with:
          pr_author: ${{ github.event.pull_request.user.login }}

  failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Perform Test
        continue-on-error: true
        uses: ./
