name: Test
on:
  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Perform Test
        uses: ./
        with:
          pr_author: "John Appleseed"

  failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Perform Test
        continue-on-error: true
        uses: ./
